% Default Figure properties
set(0, 'DefaultAxesBox'       , 'on'             ,...
'DefaultAxesFontName'  , 'Times New Roman',...
'DefaultAxesFontSize'  , 28               ,...
'DefaultAxesFontWeight', 'normal'           ,...
'DefaultaxesLineWidth' , 2               );
set(0,'DefaultPatchLineWidth' , 2)
set(0, 'DefaultTextFontName'  , 'Times New Roman',...
'DefaultTextFontSize'  , 28               ,...
'DefaultTextFontWeight', 'normal'           ,...
'DefaultLineLineWidth' , 2               );
set(0, 'defaultfigurecolor', [1 1 1]);
